version: 0.0
os: linux

# 배포할 파일 경로와 목적지 설정
files:
  - source: /
    destination: /home/ec2-user/app/  # EC2 인스턴스의 배포 디렉토리
    overwrite: yes # 기존 파일 덮어쓰기

# 파일 권한 설정
permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

# 배포 후 실행할 스크립트 설정
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user