name: daeng-ggu dev service CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  AWS_CODE_DEPLOY_APPLICATION: ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }}
  AWS_CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP }}

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout 코드
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Spotless 스타일 검사
      - name: Code style check with Spotless
        run: ./gradlew spotlessCheck

      # 프로젝트 빌드 (테스트 제외)
      - name: Build the Project
        run: ./gradlew clean build -x test

  code-deploy:
    runs-on: ubuntu-latest

    steps:
      # secrets 내용을 읽어 properties 파일을 특정 위치에 생성
      - name: make application.properties
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

        # jar 파일 복사
      - name: Copy Jar
        run: cp build/libs/*.jar ./deploy

        # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

        # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      # ZIP 파일로 압축
      - name: Make zip file
        run: zip -r ./daeng-guu-backend-0.0.1-SNAPSHOT.zip ./deploy
        shell: bash

      # AWS CLI 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 빌드된 JAR 파일을 S3로 업로드
      - name: Upload to S3
        run: aws s3 cp --region ${{ env.AWS_REGION }} ./daeng-guu-backend-0.0.1-SNAPSHOT.zip s3://${{ secrets.S3_BUCKET_NAME }}

      # CodeDeploy를 통해 EC2에 배포
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=daeng-guu-backend-0.0.1-SNAPSHOT.zip 
          --region ${{ env.AWS_REGION }}